### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by jpgreth** [markuman/sms#2]
Please add some Info, how you generated the `planet.mbtiles`. That way, others can easily extend or modify the source for their needs. 

If not suitable in this documentation, please add a link to a gist or how-to, at least.

**Comment by markuman** [comment]
MaybeI should change this URL https://github.com/markuman/sms/blob/latest/README.md#planetmbtiles to this one https://github.com/onthegomap/planetiler/blob/main/PLANET.md  
That's what I am using. Does it helps you?

**Comment by jpgreth** [comment]
Ah yes. That's what i ment. Maybe that link and some (short) kind of "that's how I did it" and I would be totally happy. ;)
