### ISSUE TITLE
Add planet.mbtiles torrent

### ISSUE THREAD

**Issue by jpgreth** [markuman/sms#3]
It would be nice to offer `planet.mbtiles` as torrent.
Offering that, could cut download times and destress the ionos source.

**Comment by markuman** [comment]
Unfortunately I got not a server nor an unmetered bandwidth, so I cannot provide a torrent file atm.  
Do you have other ideas?  
By the way. I plan to update the planet.mbtiles file this month.

**Comment by jpgreth** [comment]
Mh... ok. I just digged a bit in the behinds and HowTos of the torrent tech. I thought it would be easier. 
I just tought about any traffic limit (and/or costs) that could make you problems when hosting at ionos.
Maybe some kind of google drive / cloud storage public download could be an alternative.

If also not possible you can close this ticket.

**Comment by markuman** [comment]
> Mh... ok. I just digged a bit in the behinds and HowTos of the torrent tech. I thought it would be easier.

For torrent, you need at least **one** "computer" that is online and can serve the entire file.  
The "computer" must have enough storage (~90GB _for OS and file_) and unmetered bandwidth.   
And the download performance for other clients is only available when there are many many "computers" online, that also provides the file via torrent.

> I just tought about any traffic limit (and/or costs) that could make you problems when hosting at ionos.  
> Maybe some kind of google drive / cloud storage public download could be an alternative.

No, that is exactly why I choose ionos hidrive. No traffic limit and lower costs compared to google drive, aws s3 etc.


So I am going to close this issue.
