### ISSUE TITLE
I couldn't download the planet.mbtiles file

### ISSUE THREAD

**Issue by 10sp** [markuman/sms#5]
since its large ,not a problem, but it gets stuck around 32GB and it starts over. 
The problem happened again and again 6 times as far as I keep the account

**Comment by markuman** [comment]
@10sp what's your internet speed?  
Once it's cancled you must use the `-c` (or `--continue`) option with `wget`.  
So please try

```sh
wget --continue -O osm/planet.mbtiles https://hidrive.ionos.com/api/sharelink/download?id=SYEgScrRe
```

**Comment by exclushivity** [comment]
I will try it out
